version: '3.5'

services:
  chatgpt-clone:
    image: guestros/chatgpt-clone:latest
    container_name: chatgpt-clone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
    environment:
      - OPENAI_API_KEY=akjshdjkhasd
      - OPENAI_API_BASE=https://api.openai.com
