apiVersion: v1
kind: Namespace
metadata:
  name: chatgpt-clone
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatgpt-clone
  name: chatgpt-clone-service
  namespace: chatgpt-clone
spec:
  ports:
    - name: "1338"
      port: 1338
      targetPort: 1338
  selector:
    app: chatgpt-clone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chatgpt-clone
  name: chatgpt-clone
  namespace: chatgpt-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt-clone
  template:
    metadata:
      labels:
        app: chatgpt-clone
    spec:
      containers:
        - image: guestros/chatgpt-clone:latest
          name: chatgpt-clone
          ports:
            - containerPort: 1338
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: "500m"
              memory: 500Mi
          env:
            - name: OPENAI_API_BASE
              value: "https://api.openai.com"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: openai-api-key
      restartPolicy: Always